### ISSUE TITLE
Document required permissions for Personal Access Token

### ISSUE THREAD

**Issue by tomkerkhove** [marceloavf/github-tools-vsts#25]
Is there documentation what permissions are required when using Personal Access Token.

**Comment by marceloavf** [comment]
As far I know for a private repository you will need the entire `repo` scope and for a public repository you will need the `public_repo` scope.

But it need to be tested and documented too, I would appreciate the contribution! :raised_hands:

**Comment by tomkerkhove** [comment]
When I use this:
![image](https://user-images.githubusercontent.com/4345663/42326657-0d776bfe-806a-11e8-85fd-ce9814c1871b.png)

It will fail with error message:
> An error occured, log returned: 
Error: missing required options: repo, owner

**Comment by marceloavf** [comment]
Can you show me how you configured your task options on VSTS @tomkerkhove  ?

**Comment by tomkerkhove** [comment]
```yaml
steps:
- task: marcelo-formentao.github-tools.github-release-publish-task.GitHubReleasePublish@0
  displayName: Create or Modify GitHub Release
  inputs:
    githubEndpoint: 'Tom Kerkhove (GitHub - PAT)'
    githubReleaseAsset: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    githubReuseRelease: false

```
